// <auto-generated />
using System;
using Full_Stack_Grad_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Full_Stack_Grad_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008100049_seedV2")]
    partial class seedV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedMonths")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerPaths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Build complete web applications, from responsive React front ends to .NET APIs and databases.",
                            EstimatedMonths = 9,
                            Title = "Full-Stack Web Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Turn raw data into insights and predictions using Python, SQL and machine learning.",
                            EstimatedMonths = 8,
                            Title = "Data Scientist"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Create cross platform mobile apps that run on Android and iOS.",
                            EstimatedMonths = 6,
                            Title = "Mobile Developer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Automate, deploy and operate applications at scale in the cloud.",
                            EstimatedMonths = 7,
                            Title = "Cloud & DevOps Engineer"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Design intuitive and accessible digital experiences from research to prototype.",
                            EstimatedMonths = 4,
                            Title = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Protect organizations by finding vulnerabilities and defending systems and networks.",
                            EstimatedMonths = 6,
                            Title = "Cybersecurity Analyst"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPathProgram", b =>
                {
                    b.Property<int>("CareerPathId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CareerPathId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("CareerPathPrograms");

                    b.HasData(
                        new
                        {
                            CareerPathId = 1,
                            ProgramId = 1,
                            Order = 1
                        },
                        new
                        {
                            CareerPathId = 1,
                            ProgramId = 2,
                            Order = 2
                        },
                        new
                        {
                            CareerPathId = 2,
                            ProgramId = 3,
                            Order = 1
                        },
                        new
                        {
                            CareerPathId = 2,
                            ProgramId = 4,
                            Order = 2
                        },
                        new
                        {
                            CareerPathId = 3,
                            ProgramId = 5,
                            Order = 1
                        },
                        new
                        {
                            CareerPathId = 4,
                            ProgramId = 6,
                            Order = 1
                        },
                        new
                        {
                            CareerPathId = 4,
                            ProgramId = 2,
                            Order = 2
                        },
                        new
                        {
                            CareerPathId = 5,
                            ProgramId = 7,
                            Order = 1
                        },
                        new
                        {
                            CareerPathId = 5,
                            ProgramId = 1,
                            Order = 2
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPathSkill", b =>
                {
                    b.Property<int>("CareerPathId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CareerPathId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CareerPathSkills");

                    b.HasData(
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 4
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 5
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 6
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 15
                        },
                        new
                        {
                            CareerPathId = 1,
                            SkillId = 16
                        },
                        new
                        {
                            CareerPathId = 2,
                            SkillId = 6
                        },
                        new
                        {
                            CareerPathId = 2,
                            SkillId = 7
                        },
                        new
                        {
                            CareerPathId = 2,
                            SkillId = 8
                        },
                        new
                        {
                            CareerPathId = 2,
                            SkillId = 9
                        },
                        new
                        {
                            CareerPathId = 3,
                            SkillId = 2
                        },
                        new
                        {
                            CareerPathId = 3,
                            SkillId = 3
                        },
                        new
                        {
                            CareerPathId = 3,
                            SkillId = 14
                        },
                        new
                        {
                            CareerPathId = 3,
                            SkillId = 15
                        },
                        new
                        {
                            CareerPathId = 4,
                            SkillId = 5
                        },
                        new
                        {
                            CareerPathId = 4,
                            SkillId = 10
                        },
                        new
                        {
                            CareerPathId = 4,
                            SkillId = 11
                        },
                        new
                        {
                            CareerPathId = 4,
                            SkillId = 15
                        },
                        new
                        {
                            CareerPathId = 5,
                            SkillId = 1
                        },
                        new
                        {
                            CareerPathId = 5,
                            SkillId = 13
                        },
                        new
                        {
                            CareerPathId = 6,
                            SkillId = 12
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPopular = true,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            IsPopular = true,
                            Name = "Data Science & AI"
                        },
                        new
                        {
                            Id = 3,
                            IsPopular = true,
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 4,
                            IsPopular = false,
                            Name = "Cloud & DevOps"
                        },
                        new
                        {
                            Id = 5,
                            IsPopular = false,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 6,
                            IsPopular = true,
                            Name = "UI/UX Design"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build and style your first web pages with semantic HTML, Flexbox, Grid and responsive design.",
                            DurationHours = 12,
                            IsFeatured = true,
                            Level = "Beginner",
                            Price = 49m,
                            Status = "Published",
                            Title = "HTML & CSS Fundamentals",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master variables, functions, arrays, objects, async/await and the DOM using modern JavaScript.",
                            DurationHours = 18,
                            IsFeatured = true,
                            Level = "Beginner",
                            Price = 59m,
                            Status = "Published",
                            Title = "Modern JavaScript (ES6+)",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add static typing to your JavaScript projects with types, interfaces, generics and strict mode.",
                            DurationHours = 10,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 49m,
                            Status = "Published",
                            Title = "TypeScript Essentials",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build single page applications with components, hooks, routing and API integration in React.",
                            DurationHours = 24,
                            IsFeatured = true,
                            Level = "Intermediate",
                            Price = 79m,
                            Status = "Published",
                            Title = "React from Zero to Hero",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn C# syntax, object oriented programming, collections, LINQ and exception handling.",
                            DurationHours = 20,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 59m,
                            Status = "Published",
                            Title = "C# Programming Fundamentals",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design and build clean REST APIs with controllers, dependency injection, validation and Swagger.",
                            DurationHours = 28,
                            IsFeatured = true,
                            Level = "Intermediate",
                            Price = 89m,
                            Status = "Published",
                            Title = "Building REST APIs with ASP.NET Core",
                            Type = "Hybrid"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write SQL queries, design normalized schemas and work with joins, indexes and transactions.",
                            DurationHours = 14,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 49m,
                            Status = "Published",
                            Title = "SQL & Relational Databases",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Map your domain to a database with EF Core: relationships, migrations, queries and performance.",
                            DurationHours = 16,
                            IsFeatured = false,
                            Level = "Advanced",
                            Price = 69m,
                            Status = "Published",
                            Title = "Entity Framework Core in Depth",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Version control your code, work with branches and pull requests, and collaborate on GitHub.",
                            DurationHours = 6,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 0m,
                            Status = "Published",
                            Title = "Git & GitHub for Teams",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start programming with Python: data types, control flow, functions, files and modules.",
                            DurationHours = 16,
                            IsFeatured = true,
                            Level = "Beginner",
                            Price = 49m,
                            Status = "Published",
                            Title = "Python for Everyone",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean, transform and analyze real datasets using Pandas and NumPy in Jupyter notebooks.",
                            DurationHours = 20,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 69m,
                            Status = "Published",
                            Title = "Data Analysis with Pandas",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Turn data into interactive dashboards and reports that business teams can act on.",
                            DurationHours = 15,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 79m,
                            Status = "Published",
                            Title = "Data Visualization with Power BI",
                            Type = "Onsite"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understand supervised and unsupervised learning and build models with scikit-learn.",
                            DurationHours = 30,
                            IsFeatured = true,
                            Level = "Intermediate",
                            Price = 99m,
                            Status = "Published",
                            Title = "Machine Learning Foundations",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build neural networks for computer vision and NLP using PyTorch.",
                            DurationHours = 32,
                            IsFeatured = false,
                            Level = "Advanced",
                            Price = 129m,
                            Status = "ComingSoon",
                            Title = "Deep Learning with PyTorch",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build beautiful cross platform mobile apps for Android and iOS with Flutter and Dart.",
                            DurationHours = 26,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 79m,
                            Status = "Published",
                            Title = "Flutter Mobile Apps",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scale your Flutter apps with Bloc, Riverpod, clean architecture and testing.",
                            DurationHours = 18,
                            IsFeatured = false,
                            Level = "Advanced",
                            Price = 89m,
                            Status = "Published",
                            Title = "Advanced Flutter & State Management",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Use your React skills to ship native mobile apps with React Native and Expo.",
                            DurationHours = 14,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 69m,
                            Status = "ComingSoon",
                            Title = "React Native Crash Course",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Package and run applications in containers with Docker, images, volumes and Compose.",
                            DurationHours = 14,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 69m,
                            Status = "Published",
                            Title = "Docker & Containers",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn core cloud concepts and deploy web apps, databases and storage on Microsoft Azure.",
                            DurationHours = 18,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 79m,
                            Status = "Published",
                            Title = "Azure Cloud Fundamentals",
                            Type = "Hybrid"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automate building, testing and deploying your applications with GitHub Actions.",
                            DurationHours = 10,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 59m,
                            Status = "Published",
                            Title = "CI/CD Pipelines with GitHub Actions",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understand threats, vulnerabilities, encryption and how to protect systems and networks.",
                            DurationHours = 16,
                            IsFeatured = false,
                            Level = "Beginner",
                            Price = 59m,
                            Status = "Published",
                            Title = "Cybersecurity Essentials",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Find and exploit vulnerabilities legally using industry tools in hands-on labs.",
                            DurationHours = 36,
                            IsFeatured = false,
                            Level = "Advanced",
                            Price = 149m,
                            Status = "Published",
                            Title = "Ethical Hacking & Penetration Testing",
                            Type = "Onsite"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn user research, wireframing, visual hierarchy and usability testing.",
                            DurationHours = 12,
                            IsFeatured = true,
                            Level = "Beginner",
                            Price = 49m,
                            Status = "Published",
                            Title = "UI/UX Design Principles",
                            Type = "Online"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design interactive prototypes and design systems with components and auto layout in Figma.",
                            DurationHours = 10,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 59m,
                            Status = "Published",
                            Title = "Prototyping with Figma",
                            Type = "Recorded"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Make your websites usable for everyone by following WCAG guidelines.",
                            DurationHours = 8,
                            IsFeatured = false,
                            Level = "Intermediate",
                            Price = 39m,
                            Status = "Draft",
                            Title = "Web Accessibility Basics",
                            Type = "Online"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CourseSkill", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CourseSkills");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            SkillId = 16
                        },
                        new
                        {
                            CourseId = 3,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 4,
                            SkillId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            SkillId = 4
                        },
                        new
                        {
                            CourseId = 6,
                            SkillId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            SkillId = 4
                        },
                        new
                        {
                            CourseId = 7,
                            SkillId = 6
                        },
                        new
                        {
                            CourseId = 8,
                            SkillId = 5
                        },
                        new
                        {
                            CourseId = 8,
                            SkillId = 6
                        },
                        new
                        {
                            CourseId = 9,
                            SkillId = 15
                        },
                        new
                        {
                            CourseId = 10,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 11,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 11,
                            SkillId = 9
                        },
                        new
                        {
                            CourseId = 12,
                            SkillId = 9
                        },
                        new
                        {
                            CourseId = 13,
                            SkillId = 8
                        },
                        new
                        {
                            CourseId = 13,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 14,
                            SkillId = 8
                        },
                        new
                        {
                            CourseId = 14,
                            SkillId = 7
                        },
                        new
                        {
                            CourseId = 15,
                            SkillId = 14
                        },
                        new
                        {
                            CourseId = 16,
                            SkillId = 14
                        },
                        new
                        {
                            CourseId = 17,
                            SkillId = 3
                        },
                        new
                        {
                            CourseId = 17,
                            SkillId = 2
                        },
                        new
                        {
                            CourseId = 18,
                            SkillId = 10
                        },
                        new
                        {
                            CourseId = 19,
                            SkillId = 11
                        },
                        new
                        {
                            CourseId = 20,
                            SkillId = 15
                        },
                        new
                        {
                            CourseId = 20,
                            SkillId = 10
                        },
                        new
                        {
                            CourseId = 21,
                            SkillId = 12
                        },
                        new
                        {
                            CourseId = 22,
                            SkillId = 12
                        },
                        new
                        {
                            CourseId = 23,
                            SkillId = 13
                        },
                        new
                        {
                            CourseId = 24,
                            SkillId = 13
                        },
                        new
                        {
                            CourseId = 25,
                            SkillId = 1
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.HomepageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComingSoonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorporateDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorporateTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroSubtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomepageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComingSoonText = "New courses are launching next month!",
                            CorporateDescription = "Upskill your team with our tailored corporate training programs.",
                            CorporateTitle = "For Business",
                            HeroImageUrl = "",
                            HeroSubtitle = "Learn the most demanded skills",
                            HeroTitle = "Welcome to Andalusia Academy"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.LearningProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Go from your first HTML page to production ready React applications.",
                            DurationWeeks = 12,
                            Level = "Beginner",
                            Title = "Front-End Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build secure, data driven REST APIs with C#, ASP.NET Core, SQL Server and EF Core.",
                            DurationWeeks = 14,
                            Level = "Intermediate",
                            Title = "Back-End Development with .NET"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Collect, clean, analyze and visualize data to answer real business questions.",
                            DurationWeeks = 10,
                            Level = "Beginner",
                            Title = "Data Analysis Professional"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Build, train and evaluate machine learning and deep learning models end to end.",
                            DurationWeeks = 16,
                            Level = "Advanced",
                            Title = "Machine Learning Engineer Track"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Design and ship cross platform mobile apps for Android and iOS.",
                            DurationWeeks = 10,
                            Level = "Beginner",
                            Title = "Mobile App Development"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Automate delivery and run applications reliably in containers and the cloud.",
                            DurationWeeks = 12,
                            Level = "Intermediate",
                            Title = "DevOps & Cloud Engineering"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Research, design and prototype digital products that users love.",
                            DurationWeeks = 8,
                            Level = "Beginner",
                            Title = "Product Design (UI/UX)"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "",
                            Name = "Google Cloud"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "",
                            Name = "AWS Academy"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "",
                            Name = "Cisco Networking Academy"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "",
                            Name = "ITIDA"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.ProgramCourse", b =>
                {
                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ProgramId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("ProgramCourses");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            CourseId = 1,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 1,
                            CourseId = 2,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 1,
                            CourseId = 9,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 1,
                            CourseId = 3,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 1,
                            CourseId = 4,
                            Order = 5
                        },
                        new
                        {
                            ProgramId = 2,
                            CourseId = 5,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 2,
                            CourseId = 7,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 2,
                            CourseId = 9,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 2,
                            CourseId = 6,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 2,
                            CourseId = 8,
                            Order = 5
                        },
                        new
                        {
                            ProgramId = 3,
                            CourseId = 10,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 3,
                            CourseId = 7,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 3,
                            CourseId = 11,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 3,
                            CourseId = 12,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 4,
                            CourseId = 10,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 4,
                            CourseId = 11,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 4,
                            CourseId = 13,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 4,
                            CourseId = 14,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 5,
                            CourseId = 2,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 5,
                            CourseId = 15,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 5,
                            CourseId = 16,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 5,
                            CourseId = 17,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 6,
                            CourseId = 9,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 6,
                            CourseId = 18,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 6,
                            CourseId = 19,
                            Order = 3
                        },
                        new
                        {
                            ProgramId = 6,
                            CourseId = 20,
                            Order = 4
                        },
                        new
                        {
                            ProgramId = 7,
                            CourseId = 23,
                            Order = 1
                        },
                        new
                        {
                            ProgramId = 7,
                            CourseId = 24,
                            Order = 2
                        },
                        new
                        {
                            ProgramId = 7,
                            CourseId = 1,
                            Order = 3
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instructor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Learner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Content Manager"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HTML & CSS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Data Visualization"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Microsoft Azure"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Network Security"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 16,
                            Name = "TypeScript"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Sara Ahmed",
                            Content = "The Front-End program took me from zero to my first job in less than a year. The projects were exactly what interviewers asked about.",
                            Role = "Front-End Developer"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Omar Khaled",
                            Content = "Clear explanations, real datasets and great mentors. The Power BI course alone paid for itself.",
                            Role = "Data Analyst"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mariam Hassan",
                            Content = "I published my first Flutter app on the Play Store while still in the program.",
                            Role = "Mobile Developer"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Youssef Ali",
                            Content = "The ASP.NET Core and EF Core courses are the most practical .NET content I have found.",
                            Role = "Back-End Developer"
                        });
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPathProgram", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.CareerPath", "CareerPath")
                        .WithMany("CareerPathPrograms")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Full_Stack_Grad_Project.Model.LearningProgram", "Program")
                        .WithMany("CareerPathPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPathSkill", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.CareerPath", "CareerPath")
                        .WithMany("CareerPathSkills")
                        .HasForeignKey("CareerPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Full_Stack_Grad_Project.Model.Skill", "Skill")
                        .WithMany("CareerPathSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerPath");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Course", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CourseSkill", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.Course", "Course")
                        .WithMany("CourseSkills")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Full_Stack_Grad_Project.Model.Skill", "Skill")
                        .WithMany("CourseSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.ProgramCourse", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.Course", "Course")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Full_Stack_Grad_Project.Model.LearningProgram", "Program")
                        .WithMany("ProgramCourses")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.User", b =>
                {
                    b.HasOne("Full_Stack_Grad_Project.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.CareerPath", b =>
                {
                    b.Navigation("CareerPathPrograms");

                    b.Navigation("CareerPathSkills");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Course", b =>
                {
                    b.Navigation("CourseSkills");

                    b.Navigation("ProgramCourses");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.LearningProgram", b =>
                {
                    b.Navigation("CareerPathPrograms");

                    b.Navigation("ProgramCourses");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Full_Stack_Grad_Project.Model.Skill", b =>
                {
                    b.Navigation("CareerPathSkills");

                    b.Navigation("CourseSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
